[build]
  publish = "public"      # Directory for static files
  functions = "functions" # Directory for serverless functions

[functions]
  node_bundler = "esbuild" # Use esbuild for bundling (default)